In [2]:
import  pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# cleaning trip data

In [3]:
# reading three months data

df1 = pd.read_csv(r"C:\Project 5 (Citi Bike Project)\Data\Raw\2014-citibike-tripdata\2014-citibike-tripdata\1_January\201401-citibike-tripdata_1.csv")
df2 = pd.read_csv(r"C:\Project 5 (Citi Bike Project)\Data\Raw\2014-citibike-tripdata\2014-citibike-tripdata\2_February\201402-citibike-tripdata_1.csv")
df3 = pd.read_csv(r"C:\Project 5 (Citi Bike Project)\Data\Raw\2014-citibike-tripdata\2014-citibike-tripdata\3_March\201403-citibike-tripdata_1.csv")

In [4]:
# combining three months data

df = pd.concat([df1, df2, df3], ignore_index=True)

In [5]:
# checking the combined data

print(df.shape)
print(df.head())
print(df.tail())

(964253, 15)
   tripduration            starttime             stoptime  start station id  \
0           471  2014-01-01 00:00:06  2014-01-01 00:07:57              2009
1          1494  2014-01-01 00:00:38  2014-01-01 00:25:32               536
2           464  2014-01-01 00:03:59  2014-01-01 00:11:43               228
3           373  2014-01-01 00:05:15  2014-01-01 00:11:28               519
4           660  2014-01-01 00:05:18  2014-01-01 00:16:18                83

              start station name  start station latitude  \
0       Catherine St & Monroe St               40.711174
1                1 Ave & E 30 St               40.741444
2                E 48 St & 3 Ave               40.754601
3              Pershing Square N               40.751884
4  Atlantic Ave & Fort Greene Pl               40.683826

   start station longitude  end station id          end station name  \
0               -73.996826             263  Elizabeth St & Hester St
1               -73.975361             259   South St & Whitehall St
2               -73.971879            2022       E 59 St & Sutton Pl
3               -73.977702             526           E 33 St & 5 Ave
4               -73.976323             436  Hancock St & Bedford Ave

   end station latitude  end station longitude  bikeid    usertype birth year  \
0             40.717290             -73.996375   16379  Subscriber       1986
1             40.701221             -74.012342   15611  Subscriber       1963
2             40.758491             -73.959206   16613  Subscriber       1991
3             40.747659             -73.984907   15938  Subscriber       1989
4             40.682166             -73.953990   19830  Subscriber       1990

   gender
0       1
1       1
2       1
3       1
4       1
        tripduration            starttime             stoptime  \
964248           244  2014-03-31 23:57:47  2014-04-01 00:01:51
964249           244  2014-03-31 23:57:55  2014-04-01 00:01:59
964250           509  2014-03-31 23:58:19  2014-04-01 00:06:48
964251           649  2014-03-31 23:59:40  2014-04-01 00:10:29
964252           255  2014-03-31 23:59:54  2014-04-01 00:04:09

        start station id           start station name  start station latitude  \
964248               347     W Houston St & Hudson St               40.728739
964249               347     W Houston St & Hudson St               40.728739
964250               285           Broadway & E 14 St               40.734546
964251               403               E 2 St & 2 Ave               40.725029
964252               120  Lexington Ave & Classon Ave               40.686768

        start station longitude  end station id            end station name  \
964248               -74.007488             368          Carmine St & 6 Ave
964249               -74.007488             212     W 16 St & The High Line
964250               -73.990741             546        E 30 St & Park Ave S
964251               -73.990697             461             E 20 St & 2 Ave
964252               -73.959282             396  Lefferts Pl & Franklin Ave

        end station latitude  end station longitude  bikeid    usertype  \
964248             40.730386             -74.002150   20175  Subscriber
964249             40.743349             -74.006818   14887  Subscriber
964250             40.744449             -73.983035   19390  Subscriber
964251             40.735877             -73.982050   17356  Subscriber
964252             40.680342             -73.955769   20917  Subscriber

       birth year  gender
964248       1981       2
964249       1978       1
964250       1978       1
964251       1964       1
964252       1987       1

In [6]:
df.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='str')

In [7]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 964253
Columns: 15

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 964253 entries, 0 to 964252
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   tripduration             964253 non-null  int64
 1   starttime                964253 non-null  str
 2   stoptime                 964253 non-null  str
 3   start station id         964253 non-null  int64
 4   start station name       964253 non-null  str
 5   start station latitude   964253 non-null  float64
 6   start station longitude  964253 non-null  float64
 7   end station id           964253 non-null  int64
 8   end station name         964253 non-null  str
 9   end station latitude     964253 non-null  float64
 10  end station longitude    964253 non-null  float64
 11  bikeid                   964253 non-null  int64
 12  usertype                 964253 non-null  str
 13  birth year               964253 non-null  str
 14  gender                   964253 non-null  int64
dtypes: float64(4), int64(5), str(6)
memory usage: 110.4 MB

In [9]:
# Checking the missing values
df.isnull().sum()

tripduration               0
starttime                  0
stoptime                   0
start station id           0
start station name         0
start station latitude     0
start station longitude    0
end station id             0
end station name           0
end station latitude       0
end station longitude      0
bikeid                     0
usertype                   0
birth year                 0
gender                     0
dtype: int64

In [10]:
missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df)) * 100
})

missing

                         Missing_Count  Missing_Percentage
tripduration                         0                 0.0
starttime                            0                 0.0
stoptime                             0                 0.0
start station id                     0                 0.0
start station name                   0                 0.0
start station latitude               0                 0.0
start station longitude              0                 0.0
end station id                       0                 0.0
end station name                     0                 0.0
end station latitude                 0                 0.0
end station longitude                0                 0.0
bikeid                               0                 0.0
usertype                             0                 0.0
birth year                           0                 0.0
gender                               0                 0.0

In [11]:
# Checking the duplicate values

print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [12]:
# checking duplicate Bikeids
print("Unique bikes:", df["bikeid"].nunique())

Unique bikes: 6733

In [13]:
# Convert start and stop time

df["starttime"] = pd.to_datetime(
    df["starttime"],
    errors="coerce"
)

df["stoptime"] = pd.to_datetime(
    df["stoptime"],
    errors="coerce"
)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 964253 entries, 0 to 964252
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   tripduration             964253 non-null  int64
 1   starttime                964253 non-null  datetime64[us]
 2   stoptime                 964253 non-null  datetime64[us]
 3   start station id         964253 non-null  int64
 4   start station name       964253 non-null  str
 5   start station latitude   964253 non-null  float64
 6   start station longitude  964253 non-null  float64
 7   end station id           964253 non-null  int64
 8   end station name         964253 non-null  str
 9   end station latitude     964253 non-null  float64
 10  end station longitude    964253 non-null  float64
 11  bikeid                   964253 non-null  int64
 12  usertype                 964253 non-null  str
 13  birth year               964253 non-null  str
 14  gender                   964253 non-null  int64
dtypes: datetime64[us](2), float64(4), int64(5), str(4)
memory usage: 110.4 MB

In [15]:
# checking invalid datetimes

print("Invalid start times:", df["starttime"].isna().sum())
print("Invalid stop times:", df["stoptime"].isna().sum())

Invalid start times: 0
Invalid stop times: 0

In [16]:
# verifying trip duration

df["tripduration"].describe()

count    9.642530e+05
mean     7.583418e+02
std      3.993421e+03
min      6.000000e+01
25%      3.490000e+02
50%      5.310000e+02
75%      8.290000e+02
max      1.990440e+06
Name: tripduration, dtype: float64

In [17]:
df["trip_duration_minutes"] = df["tripduration"] / 60

In [18]:
df[["tripduration", "trip_duration_minutes"]].head()

   tripduration  trip_duration_minutes
0           471               7.850000
1          1494              24.900000
2           464               7.733333
3           373               6.216667
4           660              11.000000

In [19]:
# checking the gender

df["gender"].unique()

array([1, 2, 0])

In [20]:
# Labeling the gender

df["gender_label"] = df["gender"].map({
    0: "Unknown",
    1: "Male",
    2: "Female"
})

In [21]:
df["gender_label"].value_counts()

gender_label
Male       743200
Female     184128
Unknown     36925
Name: count, dtype: int64

In [22]:
# # Remove leading/trailing spaces and extra spaces

text_columns = df.select_dtypes(include="object").columns

print(text_columns)

Index(['start station name', 'end station name', 'usertype', 'birth year',
       'gender_label'],
      dtype='str')

C:\Users\Abdul Sofiyan\AppData\Local\Temp\ipykernel_21740\2285094528.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

In [23]:
# Remove leading/trailing spaces and extra spaces
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()
    df[col] = df[col].str.replace(r"\s+", " ", regex=True)

C:\Users\Abdul Sofiyan\AppData\Local\Temp\ipykernel_21740\2006264707.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [24]:
# making the title

df.columns = df.columns.str.strip().str.replace(r"\s+", " ", regex=True).str.title()
df

,Tripduration,Starttime,Stoptime,Start Station Id,Start Station Name,Start Station Latitude,Start Station Longitude,End Station Id,End Station Name,End Station Latitude,End Station Longitude,Bikeid,Usertype,Birth Year,Gender,Trip_Duration_Minutes,Gender_Label
0,471,2014-01-01 00:00:06,2014-01-01 00:07:57,2009,Catherine St & Monroe St,40.711174,-73.996826,263,Elizabeth St & Hester St,40.717290,-73.996375,16379,Subscriber,1986,1,7.850000,Male
1,1494,2014-01-01 00:00:38,2014-01-01 00:25:32,536,1 Ave & E 30 St,40.741444,-73.975361,259,South St & Whitehall St,40.701221,-74.012342,15611,Subscriber,1963,1,24.900000,Male
2,464,2014-01-01 00:03:59,2014-01-01 00:11:43,228,E 48 St & 3 Ave,40.754601,-73.971879,2022,E 59 St & Sutton Pl,40.758491,-73.959206,16613,Subscriber,1991,1,7.733333,Male
3,373,2014-01-01 00:05:15,2014-01-01 00:11:28,519,Pershing Square N,40.751884,-73.977702,526,E 33 St & 5 Ave,40.747659,-73.984907,15938,Subscriber,1989,1,6.216667,Male
4,660,2014-01-01 00:05:18,2014-01-01 00:16:18,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,436,Hancock St & Bedford Ave,40.682166,-73.953990,19830,Subscriber,1990,1,11.000000,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964248,244,2014-03-31 23:57:47,2014-04-01 00:01:51,347,W Houston St & Hudson St,40.728739,-74.007488,368,Carmine St & 6 Ave,40.730386,-74.002150,20175,Subscriber,1981,2,4.066667,Female
964249,244,2014-03-31 23:57:55,2014-04-01 00:01:59,347,W Houston St & Hudson St,40.728739,-74.007488,212,W 16 St & The High Line,40.743349,-74.006818,14887,Subscriber,1978,1,4.066667,Male
964250,509,2014-03-31 23:58:19,2014-04-01 00:06:48,285,Broadway & E 14 St,40.734546,-73.990741,546,E 30 St & Park Ave S,40.744449,-73.983035,19390,Subscriber,1978,1,8.483333,Male
964251,649,2014-03-31 23:59:40,2014-04-01 00:10:29,403,E 2 St & 2 Ave,40.725029,-73.990697,461,E 20 St & 2 Ave,40.735877,-73.982050,17356,Subscriber,1964,1,10.816667,Male
964252,255,2014-03-31 23:59:54,2014-04-01 00:04:09,120,Lexington Ave & Classon Ave,40.686768,-73.959282,396,Lefferts Pl & Franklin Ave,40.680342,-73.955769,20917,Subscriber,1987,1,4.250000,Male

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 964253 entries, 0 to 964252
Data columns (total 17 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Tripduration             964253 non-null  int64
 1   Starttime                964253 non-null  datetime64[us]
 2   Stoptime                 964253 non-null  datetime64[us]
 3   Start Station Id         964253 non-null  int64
 4   Start Station Name       964253 non-null  str
 5   Start Station Latitude   964253 non-null  float64
 6   Start Station Longitude  964253 non-null  float64
 7   End Station Id           964253 non-null  int64
 8   End Station Name         964253 non-null  str
 9   End Station Latitude     964253 non-null  float64
 10  End Station Longitude    964253 non-null  float64
 11  Bikeid                   964253 non-null  int64
 12  Usertype                 964253 non-null  str
 13  Birth Year               964253 non-null  str
 14  Gender                   964253 non-null  int64
 15  Trip_Duration_Minutes    964253 non-null  float64
 16  Gender_Label             964253 non-null  str
dtypes: datetime64[us](2), float64(5), int64(5), str(5)
memory usage: 125.1 MB

In [26]:
# checking the dtypes
df.dtypes

Tripduration                        int64
Starttime                  datetime64[us]
Stoptime                   datetime64[us]
Start Station Id                    int64
Start Station Name                    str
Start Station Latitude            float64
Start Station Longitude           float64
End Station Id                      int64
End Station Name                      str
End Station Latitude              float64
End Station Longitude             float64
Bikeid                              int64
Usertype                              str
Birth Year                            str
Gender                              int64
Trip_Duration_Minutes             float64
Gender_Label                          str
dtype: object

In [27]:
# # making the changes

df["Birth Year"] = pd.to_numeric(
    df["Birth Year"].replace(r"\N", np.nan)).astype("Int64")

In [28]:
df["Birth Year"].dtype

Int64Dtype()

In [29]:
df.drop("Gender",axis =1,inplace = True)
df

,Tripduration,Starttime,Stoptime,Start Station Id,Start Station Name,Start Station Latitude,Start Station Longitude,End Station Id,End Station Name,End Station Latitude,End Station Longitude,Bikeid,Usertype,Birth Year,Trip_Duration_Minutes,Gender_Label
0,471,2014-01-01 00:00:06,2014-01-01 00:07:57,2009,Catherine St & Monroe St,40.711174,-73.996826,263,Elizabeth St & Hester St,40.717290,-73.996375,16379,Subscriber,1986,7.850000,Male
1,1494,2014-01-01 00:00:38,2014-01-01 00:25:32,536,1 Ave & E 30 St,40.741444,-73.975361,259,South St & Whitehall St,40.701221,-74.012342,15611,Subscriber,1963,24.900000,Male
2,464,2014-01-01 00:03:59,2014-01-01 00:11:43,228,E 48 St & 3 Ave,40.754601,-73.971879,2022,E 59 St & Sutton Pl,40.758491,-73.959206,16613,Subscriber,1991,7.733333,Male
3,373,2014-01-01 00:05:15,2014-01-01 00:11:28,519,Pershing Square N,40.751884,-73.977702,526,E 33 St & 5 Ave,40.747659,-73.984907,15938,Subscriber,1989,6.216667,Male
4,660,2014-01-01 00:05:18,2014-01-01 00:16:18,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,436,Hancock St & Bedford Ave,40.682166,-73.953990,19830,Subscriber,1990,11.000000,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964248,244,2014-03-31 23:57:47,2014-04-01 00:01:51,347,W Houston St & Hudson St,40.728739,-74.007488,368,Carmine St & 6 Ave,40.730386,-74.002150,20175,Subscriber,1981,4.066667,Female
964249,244,2014-03-31 23:57:55,2014-04-01 00:01:59,347,W Houston St & Hudson St,40.728739,-74.007488,212,W 16 St & The High Line,40.743349,-74.006818,14887,Subscriber,1978,4.066667,Male
964250,509,2014-03-31 23:58:19,2014-04-01 00:06:48,285,Broadway & E 14 St,40.734546,-73.990741,546,E 30 St & Park Ave S,40.744449,-73.983035,19390,Subscriber,1978,8.483333,Male
964251,649,2014-03-31 23:59:40,2014-04-01 00:10:29,403,E 2 St & 2 Ave,40.725029,-73.990697,461,E 20 St & 2 Ave,40.735877,-73.982050,17356,Subscriber,1964,10.816667,Male
964252,255,2014-03-31 23:59:54,2014-04-01 00:04:09,120,Lexington Ave & Classon Ave,40.686768,-73.959282,396,Lefferts Pl & Franklin Ave,40.680342,-73.955769,20917,Subscriber,1987,4.250000,Male

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 964253 entries, 0 to 964252
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Tripduration             964253 non-null  int64
 1   Starttime                964253 non-null  datetime64[us]
 2   Stoptime                 964253 non-null  datetime64[us]
 3   Start Station Id         964253 non-null  int64
 4   Start Station Name       964253 non-null  str
 5   Start Station Latitude   964253 non-null  float64
 6   Start Station Longitude  964253 non-null  float64
 7   End Station Id           964253 non-null  int64
 8   End Station Name         964253 non-null  str
 9   End Station Latitude     964253 non-null  float64
 10  End Station Longitude    964253 non-null  float64
 11  Bikeid                   964253 non-null  int64
 12  Usertype                 964253 non-null  str
 13  Birth Year               927400 non-null  Int64
 14  Trip_Duration_Minutes    964253 non-null  float64
 15  Gender_Label             964253 non-null  str
dtypes: Int64(1), datetime64[us](2), float64(5), int64(4), str(4)
memory usage: 118.6 MB

In [31]:
df.columns = (
    df.columns
    .str.replace(" ", "_")
)

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 964253 entries, 0 to 964252
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Tripduration             964253 non-null  int64
 1   Starttime                964253 non-null  datetime64[us]
 2   Stoptime                 964253 non-null  datetime64[us]
 3   Start_Station_Id         964253 non-null  int64
 4   Start_Station_Name       964253 non-null  str
 5   Start_Station_Latitude   964253 non-null  float64
 6   Start_Station_Longitude  964253 non-null  float64
 7   End_Station_Id           964253 non-null  int64
 8   End_Station_Name         964253 non-null  str
 9   End_Station_Latitude     964253 non-null  float64
 10  End_Station_Longitude    964253 non-null  float64
 11  Bikeid                   964253 non-null  int64
 12  Usertype                 964253 non-null  str
 13  Birth_Year               927400 non-null  Int64
 14  Trip_Duration_Minutes    964253 non-null  float64
 15  Gender_Label             964253 non-null  str
dtypes: Int64(1), datetime64[us](2), float64(5), int64(4), str(4)
memory usage: 118.6 MB

In [33]:
df.columns = df.columns.str.replace({"Tripduration": "Trip_Duration","Starttime":"Start_Time","Stoptime":"Stop_Time","Bikeid":"Bike_Id","Usertype":"User_Type"})
df

,Trip_Duration,Start_Time,Stop_Time,Start_Station_Id,Start_Station_Name,Start_Station_Latitude,Start_Station_Longitude,End_Station_Id,End_Station_Name,End_Station_Latitude,End_Station_Longitude,Bike_Id,User_Type,Birth_Year,Trip_Duration_Minutes,Gender_Label
0,471,2014-01-01 00:00:06,2014-01-01 00:07:57,2009,Catherine St & Monroe St,40.711174,-73.996826,263,Elizabeth St & Hester St,40.717290,-73.996375,16379,Subscriber,1986,7.850000,Male
1,1494,2014-01-01 00:00:38,2014-01-01 00:25:32,536,1 Ave & E 30 St,40.741444,-73.975361,259,South St & Whitehall St,40.701221,-74.012342,15611,Subscriber,1963,24.900000,Male
2,464,2014-01-01 00:03:59,2014-01-01 00:11:43,228,E 48 St & 3 Ave,40.754601,-73.971879,2022,E 59 St & Sutton Pl,40.758491,-73.959206,16613,Subscriber,1991,7.733333,Male
3,373,2014-01-01 00:05:15,2014-01-01 00:11:28,519,Pershing Square N,40.751884,-73.977702,526,E 33 St & 5 Ave,40.747659,-73.984907,15938,Subscriber,1989,6.216667,Male
4,660,2014-01-01 00:05:18,2014-01-01 00:16:18,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,436,Hancock St & Bedford Ave,40.682166,-73.953990,19830,Subscriber,1990,11.000000,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964248,244,2014-03-31 23:57:47,2014-04-01 00:01:51,347,W Houston St & Hudson St,40.728739,-74.007488,368,Carmine St & 6 Ave,40.730386,-74.002150,20175,Subscriber,1981,4.066667,Female
964249,244,2014-03-31 23:57:55,2014-04-01 00:01:59,347,W Houston St & Hudson St,40.728739,-74.007488,212,W 16 St & The High Line,40.743349,-74.006818,14887,Subscriber,1978,4.066667,Male
964250,509,2014-03-31 23:58:19,2014-04-01 00:06:48,285,Broadway & E 14 St,40.734546,-73.990741,546,E 30 St & Park Ave S,40.744449,-73.983035,19390,Subscriber,1978,8.483333,Male
964251,649,2014-03-31 23:59:40,2014-04-01 00:10:29,403,E 2 St & 2 Ave,40.725029,-73.990697,461,E 20 St & 2 Ave,40.735877,-73.982050,17356,Subscriber,1964,10.816667,Male
964252,255,2014-03-31 23:59:54,2014-04-01 00:04:09,120,Lexington Ave & Classon Ave,40.686768,-73.959282,396,Lefferts Pl & Franklin Ave,40.680342,-73.955769,20917,Subscriber,1987,4.250000,Male

In [34]:
df.columns

Index(['Trip_Duration', 'Start_Time', 'Stop_Time', 'Start_Station_Id',
       'Start_Station_Name', 'Start_Station_Latitude',
       'Start_Station_Longitude', 'End_Station_Id', 'End_Station_Name',
       'End_Station_Latitude', 'End_Station_Longitude', 'Bike_Id', 'User_Type',
       'Birth_Year', 'Trip_Duration_Minutes', 'Gender_Label'],
      dtype='str')

# cleaning station data

In [35]:
import json
from urllib.request import urlopen

import pandas as pd

url = "https://gbfs.citibikenyc.com/gbfs/en/station_information.json"
with urlopen(url) as response:
    data = json.load(response)

stations = pd.DataFrame(data["data"]["stations"])
stations.to_csv("station_information.csv", index=False)

print(stations.head())

                             station_id                           name  \
0                   2250950615627071938        Blake Ave & Schenck Ave
1  b4a320d6-2611-4940-96ca-17fb297ec826  Sunken Meadow Comfort Station
2  3d68a3fd-91da-49e8-9cd5-69b333863789         Nagle Ave & Ellwood St
3  faf98f78-51ab-4248-b7e7-f402902385a6               65 St & Broadway
4  7938263e-e5b8-4ca7-b8bf-1adbaae5fead       Southern Blvd & E 149 St

  short_name        lon        lat region_id  capacity  \
0    3883.06 -73.887380  40.669000        71        16
1    7571.01 -73.919060  40.795580        71        25
2    8528.05 -73.928489  40.860120        71        21
3    6417.11 -73.897388  40.749372        71        18
4    7788.13 -73.904192  40.811892        71        27

                                         rental_uris     rental_methods  \
0  {'android': 'https://bkn.lft.to/lastmile_qr_sc...  [KEY, CREDITCARD]
1  {'android': 'https://bkn.lft.to/lastmile_qr_sc...  [KEY, CREDITCARD]
2  {'android': 'https://bkn.lft.to/lastmile_qr_sc...  [KEY, CREDITCARD]
3  {'android': 'https://bkn.lft.to/lastmile_qr_sc...  [KEY, CREDITCARD]
4  {'android': 'https://bkn.lft.to/lastmile_qr_sc...  [KEY, CREDITCARD]

   has_kiosk station_type                           external_id  \
0      False      classic                   2250950615627071938
1       True      classic  b4a320d6-2611-4940-96ca-17fb297ec826
2       True      classic  3d68a3fd-91da-49e8-9cd5-69b333863789
3       True      classic  faf98f78-51ab-4248-b7e7-f402902385a6
4       True      classic  7938263e-e5b8-4ca7-b8bf-1adbaae5fead

   electric_bike_surcharge_waiver eightd_station_services  \
0                           False                      []
1                           False                      []
2                           False                      []
3                           False                      []
4                           False                      []

   eightd_has_key_dispenser
0                     False
1                     False
2                     False
3                     False
4                     False

In [36]:
df5 = pd.read_csv(r"C:\Project 5 (Citi Bike Project)\Data\Raw\station_information.csv")

In [37]:
df5.head()

,station_id,name,short_name,lon,lat,region_id,capacity,rental_uris,rental_methods,has_kiosk,station_type,external_id,electric_bike_surcharge_waiver,eightd_station_services,eightd_has_key_dispenser
0,2250953816197165238,New Lots Ave & Van Sinderen Ave,3565.07,-73.899150,40.659230,71.0,16,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",False,classic,2250953816197165238,False,[],False
1,18eccc71-66be-4e4c-8335-095a9bf0df94,Adam Clayton Powell Blvd & W 126 St,7738.04,-73.947765,40.809495,71.0,33,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,18eccc71-66be-4e4c-8335-095a9bf0df94,False,[],False
2,1822663031356509142,Matthews Ct & Coney Island Ave,3034.02,-73.969510,40.642350,71.0,0,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,1822663031356509142,False,[],False
3,7a6fc75f-a605-4dd6-b567-b2bbbfb862f3,65 Pl & 53 Ave,5764.02,-73.900220,40.731450,71.0,19,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,7a6fc75f-a605-4dd6-b567-b2bbbfb862f3,False,[],False
4,2235294222661977076,Livonia Ave & Powell St,3678.05,-73.902310,40.663630,71.0,0,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",False,classic,2235294222661977076,False,[],False

In [38]:
df5.columns

Index(['station_id', 'name', 'short_name', 'lon', 'lat', 'region_id',
       'capacity', 'rental_uris', 'rental_methods', 'has_kiosk',
       'station_type', 'external_id', 'electric_bike_surcharge_waiver',
       'eightd_station_services', 'eightd_has_key_dispenser'],
      dtype='str')

In [39]:
# dropping unnecessary columns

df5 = df5.drop(columns=[
    "short_name",
    "region_id",
    "rental_uris",
    "rental_methods",
    "external_id",
    "electric_bike_surcharge_waiver",
    "eightd_station_services",
    "eightd_has_key_dispenser"
])

In [40]:
df5.info()

<class 'pandas.DataFrame'>
RangeIndex: 2520 entries, 0 to 2519
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   station_id    2520 non-null   str
 1   name          2520 non-null   str
 2   lon           2520 non-null   float64
 3   lat           2520 non-null   float64
 4   capacity      2520 non-null   int64
 5   has_kiosk     2520 non-null   bool
 6   station_type  2520 non-null   str
dtypes: bool(1), float64(2), int64(1), str(3)
memory usage: 120.7 KB

In [41]:
# checking duplicate stations

df5["station_id"].duplicated().sum()

np.int64(0)

In [42]:
# Cleaning station names

df5["name"] = (
    df5["name"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)
df5.name

0                New Lots Ave & Van Sinderen Ave
1            Adam Clayton Powell Blvd & W 126 St
2                 Matthews Ct & Coney Island Ave
3                                 65 Pl & 53 Ave
4                        Livonia Ave & Powell St
                          ...
2515                               Fairmount Ave
2516                         Garfield Light Rail
2517               Arlington Ave & Wilkinson Ave
2518                            Wade St & MLK Dr
2519    Hoboken Terminal - Hudson St & Hudson Pl
Name: name, Length: 2520, dtype: str

In [43]:
# Cleaning numeric columns

df5["station_id"] = pd.to_numeric(
    df5["station_id"], errors="coerce"
)

df5["lat"] = pd.to_numeric(
    df5["lat"], errors="coerce"
)

df5["lon"] = pd.to_numeric(
    df5["lon"], errors="coerce"
)

df5["capacity"] = pd.to_numeric(
    df5["capacity"], errors="coerce"
)

In [44]:
# removing null values

df5.isnull().sum()

station_id      1811
name               0
lon                0
lat                0
capacity           0
has_kiosk          0
station_type       0
dtype: int64

In [45]:
df5[df5["station_id"].isna()].head()

,station_id,name,lon,lat,capacity,has_kiosk,station_type
1,NaN,Adam Clayton Powell Blvd & W 126 St,-73.947765,40.809495,33,True,classic
3,NaN,65 Pl & 53 Ave,-73.900220,40.731450,19,True,classic
5,NaN,Barrow St & Hudson St,-74.006744,40.731724,45,True,classic
6,NaN,Vesey St & Church St,-74.010472,40.712220,78,True,classic
8,NaN,61 St & Borden Ave,-73.904170,40.725580,0,True,classic

In [46]:
df5 = df5.dropna(subset=["station_id"])
df5["station_id"].isna().sum()

np.int64(0)

In [47]:
df5[
    (df5["lat"].isna()) |
    (df5["lon"].isna())
]
df5[["lat", "lon"]].describe()

              lat         lon
count  709.000000  709.000000
mean    40.731100  -73.927247
std      0.074033    0.060006
min     40.611240  -74.098110
25%     40.666020  -73.963160
50%     40.729730  -73.907540
75%     40.758400  -73.882550
max     40.912390  -73.832260

In [48]:
df5.loc[
    df5["capacity"] <= 0,
    "capacity"
] = np.nan

In [49]:
# renaming and replacing

df5 = df5.rename(columns={
    "station_id": "Station Id",
    "name": "Name",
    "lon": "Longitude",
    "lat": "Latitude",
    "capacity": "Capacity",
    "has_kiosk": "Has Kiosk",
    "station_type": "Station Type"
})

In [50]:
df5.info()

<class 'pandas.DataFrame'>
Index: 709 entries, 0 to 2518
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Station Id    709 non-null    float64
 1   Name          709 non-null    str
 2   Longitude     709 non-null    float64
 3   Latitude      709 non-null    float64
 4   Capacity      686 non-null    float64
 5   Has Kiosk     709 non-null    bool
 6   Station Type  709 non-null    str
dtypes: bool(1), float64(4), str(2)
memory usage: 39.5 KB

In [51]:
df5.columns

Index(['Station Id', 'Name', 'Longitude', 'Latitude', 'Capacity', 'Has Kiosk',
       'Station Type'],
      dtype='str')

In [52]:
print(df5.head())
print(df5['Station Id'].head(20).tolist())
print(df5['Station Id'].dtype)

     Station Id                             Name  Longitude   Latitude  \
0  2.250954e+18  New Lots Ave & Van Sinderen Ave -73.899150  40.659230
2  1.822663e+18   Matthews Ct & Coney Island Ave -73.969510  40.642350
4  2.235294e+18          Livonia Ave & Powell St -73.902310  40.663630
7  1.986708e+18                   21 St & 20 Ave -73.912731  40.783936
9  1.795147e+18        Longfellow Ave & Aldus St -73.887629  40.823194

   Capacity  Has Kiosk Station Type
0      16.0      False      classic
2       NaN       True      classic
4       NaN      False      classic
7      19.0       True      classic
9      24.0       True      classic
[2.2509538161971648e+18, 1.8226630313565087e+18, 2.2352942226619768e+18, 1.9867079770014953e+18, 1.795146692060861e+18, 1.8352469375175437e+18, 2.2638496451964296e+18, 2.250954679485592e+18, 2.1240369947349512e+18, 2.1240372502668849e+18, 2.1719034888845235e+18, 2.12442630797308e+18, 2.1266230071923576e+18, 1.8490096546267464e+18, 1.840540852548304e+18, 1.8405041380400456e+18, 1.859438049977969e+18, 1.8311783522655624e+18, 2.2509527588157527e+18, 1.8754151447605765e+18]
float64

# cleaning weather data

In [53]:
df4 = pd.read_csv(r"C:\Project 5 (Citi Bike Project)\Data\Raw\Weather_data.csv",skiprows=2)

In [54]:
df4.info()
df4.isnull().sum()
df4.head()

<class 'pandas.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   time                      2160 non-null   str
 1   temperature_2m (°C)       2160 non-null   float64
 2   relative_humidity_2m (%)  2160 non-null   int64
 3   precipitation (mm)        2160 non-null   float64
 4   wind_speed_10m (km/h)     2160 non-null   float64
 5   wind_direction_10m (°)    2160 non-null   int64
 6   weather_code (wmo code)   2160 non-null   int64
dtypes: float64(3), int64(3), str(1)
memory usage: 118.3 KB

,time,temperature_2m (°C),relative_humidity_2m (%),precipitation (mm),wind_speed_10m (km/h),wind_direction_10m (°),weather_code (wmo code)
0,2014-01-01T00:00,-3.6,44,0.0,15.0,281,0
1,2014-01-01T01:00,-4.0,43,0.0,14.1,283,0
2,2014-01-01T02:00,-4.4,45,0.0,11.9,273,0
3,2014-01-01T03:00,-4.6,46,0.0,10.8,268,0
4,2014-01-01T04:00,-4.7,46,0.0,10.9,261,0

In [55]:
# making valid changes in time

df4["time"] = pd.to_datetime(df4["time"])
df4.time

0      2014-01-01 00:00:00
1      2014-01-01 01:00:00
2      2014-01-01 02:00:00
3      2014-01-01 03:00:00
4      2014-01-01 04:00:00
               ...
2155   2014-03-31 19:00:00
2156   2014-03-31 20:00:00
2157   2014-03-31 21:00:00
2158   2014-03-31 22:00:00
2159   2014-03-31 23:00:00
Name: time, Length: 2160, dtype: datetime64[us]

In [56]:
# checking duplicate values

df4["time"].duplicated().sum()

np.int64(0)

In [57]:
# checking the date range

print(df4["time"].min())
print(df4["time"].max())

2014-01-01 00:00:00
2014-03-31 23:00:00

In [58]:
# capitilizing the first letters

df4.columns = df4.columns.str.title()

In [59]:
df4.info

<bound method DataFrame.info of                     Time  Temperature_2M (°C)  Relative_Humidity_2M (%)  \
0    2014-01-01 00:00:00                 -3.6                        44
1    2014-01-01 01:00:00                 -4.0                        43
2    2014-01-01 02:00:00                 -4.4                        45
3    2014-01-01 03:00:00                 -4.6                        46
4    2014-01-01 04:00:00                 -4.7                        46
...                  ...                  ...                       ...
2155 2014-03-31 19:00:00                 10.0                        49
2156 2014-03-31 20:00:00                  7.9                        53
2157 2014-03-31 21:00:00                  6.5                        56
2158 2014-03-31 22:00:00                  5.4                        58
2159 2014-03-31 23:00:00                  4.5                        60

      Precipitation (Mm)  Wind_Speed_10M (Km/H)  Wind_Direction_10M (°)  \
0                    0.0                   15.0                     281
1                    0.0                   14.1                     283
2                    0.0                   11.9                     273
3                    0.0                   10.8                     268
4                    0.0                   10.9                     261
...                  ...                    ...                     ...
2155                 0.0                    9.8                     343
2156                 0.0                   11.9                     355
2157                 0.0                   14.4                       4
2158                 0.0                   15.9                       5
2159                 0.0                   15.5                       1

      Weather_Code (Wmo Code)
0                           0
1                           0
2                           0
3                           0
4                           0
...                       ...
2155                        0
2156                        0
2157                        0
2158                        0
2159                        0

[2160 rows x 7 columns]>

In [60]:
df4.columns

Index(['Time', 'Temperature_2M (°C)', 'Relative_Humidity_2M (%)',
       'Precipitation (Mm)', 'Wind_Speed_10M (Km/H)', 'Wind_Direction_10M (°)',
       'Weather_Code (Wmo Code)'],
      dtype='str')

# Merging three datasets (Trip data,Station data,Weather data)

In [61]:
print(df[['Start_Station_Id', 'End_Station_Id']].dtypes)

print(df5[['Station Id']].dtypes)

print(df['Start_Time'].dtype)
print(df4['Time'].dtype)

Start_Station_Id    int64
End_Station_Id      int64
dtype: object
Station Id    float64
dtype: object
datetime64[us]
datetime64[us]

In [62]:
df5['Station Id'] = pd.to_numeric(
    df5['Station Id'],
    errors='coerce'
).astype('Int64')

In [63]:
df['Start_Station_Id'] = df['Start_Station_Id'].astype('Int64')
df['End_Station_Id'] = df['End_Station_Id'].astype('Int64')

In [64]:
# Merging the station data

# Start station
start_station = df5.rename(columns={
    'Station Id': 'Start_Station_Id',
    'Name': 'Station_Name_Start',
    'Longitude': 'Station_Longitude_Start',
    'Latitude': 'Station_Latitude_Start',
    'Capacity': 'Station_Capacity_Start',
    'Has Kiosk': 'Has_Kiosk_Start',
    'Station Type': 'Station_Type_Start'
})

merged_df = df.merge(
    start_station,
    on='Start_Station_Id',
    how='left'
)

In [65]:
# End Station
end_station = df5.rename(columns={
    'Station Id': 'End_Station_Id',
    'Name': 'Station_Name_End',
    'Longitude': 'Station_Longitude_End',
    'Latitude': 'Station_Latitude_End',
    'Capacity': 'Station_Capacity_End',
    'Has Kiosk': 'Has_Kiosk_End',
    'Station Type': 'Station_Type_End'
})

merged_df = merged_df.merge(
    end_station,
    on='End_Station_Id',
    how='left'
)

In [66]:
# Checking the merged data
print(merged_df.shape)

(964253, 28)

In [67]:
# Merging the weather data

# Creating the hourly key
merged_df['Weather_Time'] = merged_df['Start_Time'].dt.floor('h')

In [68]:
final_df = merged_df.merge(
    df4,
    left_on='Weather_Time',
    right_on='Time',
    how='left'
)

In [69]:
print(final_df.shape)
print(final_df.head())

(964253, 36)
   Trip_Duration          Start_Time           Stop_Time  Start_Station_Id  \
0            471 2014-01-01 00:00:06 2014-01-01 00:07:57              2009
1           1494 2014-01-01 00:00:38 2014-01-01 00:25:32               536
2            464 2014-01-01 00:03:59 2014-01-01 00:11:43               228
3            373 2014-01-01 00:05:15 2014-01-01 00:11:28               519
4            660 2014-01-01 00:05:18 2014-01-01 00:16:18                83

              Start_Station_Name  Start_Station_Latitude  \
0       Catherine St & Monroe St               40.711174
1                1 Ave & E 30 St               40.741444
2                E 48 St & 3 Ave               40.754601
3              Pershing Square N               40.751884
4  Atlantic Ave & Fort Greene Pl               40.683826

   Start_Station_Longitude  End_Station_Id          End_Station_Name  \
0               -73.996826             263  Elizabeth St & Hester St
1               -73.975361             259   South St & Whitehall St
2               -73.971879            2022       E 59 St & Sutton Pl
3               -73.977702             526           E 33 St & 5 Ave
4               -73.976323             436  Hancock St & Bedford Ave

   End_Station_Latitude  ...  Has_Kiosk_End  Station_Type_End Weather_Time  \
0             40.717290  ...            NaN               NaN   2014-01-01
1             40.701221  ...            NaN               NaN   2014-01-01
2             40.758491  ...            NaN               NaN   2014-01-01
3             40.747659  ...            NaN               NaN   2014-01-01
4             40.682166  ...            NaN               NaN   2014-01-01

        Time  Temperature_2M (°C) Relative_Humidity_2M (%) Precipitation (Mm)  \
0 2014-01-01                 -3.6                       44                0.0
1 2014-01-01                 -3.6                       44                0.0
2 2014-01-01                 -3.6                       44                0.0
3 2014-01-01                 -3.6                       44                0.0
4 2014-01-01                 -3.6                       44                0.0

   Wind_Speed_10M (Km/H)  Wind_Direction_10M (°)  Weather_Code (Wmo Code)
0                   15.0                     281                        0
1                   15.0                     281                        0
2                   15.0                     281                        0
3                   15.0                     281                        0
4                   15.0                     281                        0

[5 rows x 36 columns]

In [70]:
station_columns_to_remove = [
    'Station_Name_Start',
    'Station_Longitude_Start',
    'Station_Latitude_Start',
    'Station_Capacity_Start',
    'Has_Kiosk_Start',
    'Station_Type_Start',
    'Station_Name_End',
    'Station_Longitude_End',
    'Station_Latitude_End',
    'Station_Capacity_End',
    'Has_Kiosk_End',
    'Station_Type_End'
]

final_df = final_df.drop(columns=station_columns_to_remove)

In [71]:
print(final_df.shape)
print(final_df.columns)

(964253, 24)
Index(['Trip_Duration', 'Start_Time', 'Stop_Time', 'Start_Station_Id',
       'Start_Station_Name', 'Start_Station_Latitude',
       'Start_Station_Longitude', 'End_Station_Id', 'End_Station_Name',
       'End_Station_Latitude', 'End_Station_Longitude', 'Bike_Id', 'User_Type',
       'Birth_Year', 'Trip_Duration_Minutes', 'Gender_Label', 'Weather_Time',
       'Time', 'Temperature_2M (°C)', 'Relative_Humidity_2M (%)',
       'Precipitation (Mm)', 'Wind_Speed_10M (Km/H)', 'Wind_Direction_10M (°)',
       'Weather_Code (Wmo Code)'],
      dtype='str')

In [72]:
missing_percent = (final_df.isnull().sum() / len(final_df)) * 100

print(missing_percent.sort_values(ascending=False))

Birth_Year                  3.821922
Trip_Duration               0.000000
Stop_Time                   0.000000
Start_Time                  0.000000
Start_Station_Name          0.000000
Start_Station_Latitude      0.000000
Start_Station_Longitude     0.000000
Start_Station_Id            0.000000
End_Station_Id              0.000000
End_Station_Name            0.000000
End_Station_Longitude       0.000000
End_Station_Latitude        0.000000
Bike_Id                     0.000000
User_Type                   0.000000
Trip_Duration_Minutes       0.000000
Gender_Label                0.000000
Weather_Time                0.000000
Time                        0.000000
Temperature_2M (°C)         0.000000
Relative_Humidity_2M (%)    0.000000
Precipitation (Mm)          0.000000
Wind_Speed_10M (Km/H)       0.000000
Wind_Direction_10M (°)      0.000000
Weather_Code (Wmo Code)     0.000000
dtype: float64

In [73]:
print(final_df.isnull().sum())

Trip_Duration                   0
Start_Time                      0
Stop_Time                       0
Start_Station_Id                0
Start_Station_Name              0
Start_Station_Latitude          0
Start_Station_Longitude         0
End_Station_Id                  0
End_Station_Name                0
End_Station_Latitude            0
End_Station_Longitude           0
Bike_Id                         0
User_Type                       0
Birth_Year                  36853
Trip_Duration_Minutes           0
Gender_Label                    0
Weather_Time                    0
Time                            0
Temperature_2M (°C)             0
Relative_Humidity_2M (%)        0
Precipitation (Mm)              0
Wind_Speed_10M (Km/H)           0
Wind_Direction_10M (°)          0
Weather_Code (Wmo Code)         0
dtype: int64

In [74]:
final_df.to_csv(
    "1.1CitiBike_Final_Cleaned_Data.csv",
    index=False
)