In [14]:
import pandas as pd

In [15]:
fe = pd.read_csv(r"C:\Project 5 (Citi Bike Project)\1.1_CitiBike_Final_Cleaned_Data.csv")
fe

,Trip_Duration,Start_Time,Stop_Time,Start_Station_Id,Start_Station_Name,Start_Station_Latitude,Start_Station_Longitude,End_Station_Id,End_Station_Name,End_Station_Latitude,...,Trip_Duration_Minutes,Gender_Label,Weather_Time,Time,Temperature_2M (°C),Relative_Humidity_2M (%),Precipitation (Mm),Wind_Speed_10M (Km/H),Wind_Direction_10M (°),Weather_Code (Wmo Code)
0,471,2014-01-01 00:00:06,2014-01-01 00:07:57,2009,Catherine St & Monroe St,40.711174,-73.996826,263,Elizabeth St & Hester St,40.717290,...,7.850000,Male,2014-01-01 00:00:00,2014-01-01 00:00:00,-3.6,44,0.0,15.0,281,0
1,1494,2014-01-01 00:00:38,2014-01-01 00:25:32,536,1 Ave & E 30 St,40.741444,-73.975361,259,South St & Whitehall St,40.701221,...,24.900000,Male,2014-01-01 00:00:00,2014-01-01 00:00:00,-3.6,44,0.0,15.0,281,0
2,464,2014-01-01 00:03:59,2014-01-01 00:11:43,228,E 48 St & 3 Ave,40.754601,-73.971879,2022,E 59 St & Sutton Pl,40.758491,...,7.733333,Male,2014-01-01 00:00:00,2014-01-01 00:00:00,-3.6,44,0.0,15.0,281,0
3,373,2014-01-01 00:05:15,2014-01-01 00:11:28,519,Pershing Square N,40.751884,-73.977702,526,E 33 St & 5 Ave,40.747659,...,6.216667,Male,2014-01-01 00:00:00,2014-01-01 00:00:00,-3.6,44,0.0,15.0,281,0
4,660,2014-01-01 00:05:18,2014-01-01 00:16:18,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,436,Hancock St & Bedford Ave,40.682166,...,11.000000,Male,2014-01-01 00:00:00,2014-01-01 00:00:00,-3.6,44,0.0,15.0,281,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964248,244,2014-03-31 23:57:47,2014-04-01 00:01:51,347,W Houston St & Hudson St,40.728739,-74.007488,368,Carmine St & 6 Ave,40.730386,...,4.066667,Female,2014-03-31 23:00:00,2014-03-31 23:00:00,4.5,60,0.0,15.5,1,0
964249,244,2014-03-31 23:57:55,2014-04-01 00:01:59,347,W Houston St & Hudson St,40.728739,-74.007488,212,W 16 St & The High Line,40.743349,...,4.066667,Male,2014-03-31 23:00:00,2014-03-31 23:00:00,4.5,60,0.0,15.5,1,0
964250,509,2014-03-31 23:58:19,2014-04-01 00:06:48,285,Broadway & E 14 St,40.734546,-73.990741,546,E 30 St & Park Ave S,40.744449,...,8.483333,Male,2014-03-31 23:00:00,2014-03-31 23:00:00,4.5,60,0.0,15.5,1,0
964251,649,2014-03-31 23:59:40,2014-04-01 00:10:29,403,E 2 St & 2 Ave,40.725029,-73.990697,461,E 20 St & 2 Ave,40.735877,...,10.816667,Male,2014-03-31 23:00:00,2014-03-31 23:00:00,4.5,60,0.0,15.5,1,0
964252,255,2014-03-31 23:59:54,2014-04-01 00:04:09,120,Lexington Ave & Classon Ave,40.686768,-73.959282,396,Lefferts Pl & Franklin Ave,40.680342,...,4.250000,Male,2014-03-31 23:00:00,2014-03-31 23:00:00,4.5,60,0.0,15.5,1,0

In [ ]:
fe["Start_Time"] = pd.to_datetime(fe["Start_Time"])
fe["Stop_Time"] = pd.to_datetime(fe["Stop_Time"])
fe["Weather_Time"] = pd.to_datetime(fe["Weather_Time"])
fe["Time"] = pd.to_datetime(fe["Time"])

In [27]:
# Time-based features

fe["Start_Hour"] = fe["Start_Time"].dt.hour
fe

,Trip_Duration,Start_Time,Stop_Time,Start_Station_Id,Start_Station_Name,Start_Station_Latitude,Start_Station_Longitude,End_Station_Id,End_Station_Name,End_Station_Latitude,...,Precipitation (Mm),Wind_Speed_10M (Km/H),Wind_Direction_10M (°),Weather_Code (Wmo Code),Start_Hour,Day_of_Week,Day_Type,Month,Peak_Hour,Season
0,471,2014-01-01 00:00:06,2014-01-01 00:07:57,2009,Catherine St & Monroe St,40.711174,-73.996826,263,Elizabeth St & Hester St,40.717290,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
1,1494,2014-01-01 00:00:38,2014-01-01 00:25:32,536,1 Ave & E 30 St,40.741444,-73.975361,259,South St & Whitehall St,40.701221,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
2,464,2014-01-01 00:03:59,2014-01-01 00:11:43,228,E 48 St & 3 Ave,40.754601,-73.971879,2022,E 59 St & Sutton Pl,40.758491,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
3,373,2014-01-01 00:05:15,2014-01-01 00:11:28,519,Pershing Square N,40.751884,-73.977702,526,E 33 St & 5 Ave,40.747659,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
4,660,2014-01-01 00:05:18,2014-01-01 00:16:18,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,436,Hancock St & Bedford Ave,40.682166,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964248,244,2014-03-31 23:57:47,2014-04-01 00:01:51,347,W Houston St & Hudson St,40.728739,-74.007488,368,Carmine St & 6 Ave,40.730386,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964249,244,2014-03-31 23:57:55,2014-04-01 00:01:59,347,W Houston St & Hudson St,40.728739,-74.007488,212,W 16 St & The High Line,40.743349,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964250,509,2014-03-31 23:58:19,2014-04-01 00:06:48,285,Broadway & E 14 St,40.734546,-73.990741,546,E 30 St & Park Ave S,40.744449,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964251,649,2014-03-31 23:59:40,2014-04-01 00:10:29,403,E 2 St & 2 Ave,40.725029,-73.990697,461,E 20 St & 2 Ave,40.735877,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964252,255,2014-03-31 23:59:54,2014-04-01 00:04:09,120,Lexington Ave & Classon Ave,40.686768,-73.959282,396,Lefferts Pl & Franklin Ave,40.680342,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring

In [18]:
fe["Day_of_Week"] = fe["Start_Time"].dt.day_name()
fe

,Trip_Duration,Start_Time,Stop_Time,Start_Station_Id,Start_Station_Name,Start_Station_Latitude,Start_Station_Longitude,End_Station_Id,End_Station_Name,End_Station_Latitude,...,Weather_Time,Time,Temperature_2M (°C),Relative_Humidity_2M (%),Precipitation (Mm),Wind_Speed_10M (Km/H),Wind_Direction_10M (°),Weather_Code (Wmo Code),Start_Hour,Day_of_Week
0,471,2014-01-01 00:00:06,2014-01-01 00:07:57,2009,Catherine St & Monroe St,40.711174,-73.996826,263,Elizabeth St & Hester St,40.717290,...,2014-01-01 00:00:00,2014-01-01 00:00:00,-3.6,44,0.0,15.0,281,0,0,Wednesday
1,1494,2014-01-01 00:00:38,2014-01-01 00:25:32,536,1 Ave & E 30 St,40.741444,-73.975361,259,South St & Whitehall St,40.701221,...,2014-01-01 00:00:00,2014-01-01 00:00:00,-3.6,44,0.0,15.0,281,0,0,Wednesday
2,464,2014-01-01 00:03:59,2014-01-01 00:11:43,228,E 48 St & 3 Ave,40.754601,-73.971879,2022,E 59 St & Sutton Pl,40.758491,...,2014-01-01 00:00:00,2014-01-01 00:00:00,-3.6,44,0.0,15.0,281,0,0,Wednesday
3,373,2014-01-01 00:05:15,2014-01-01 00:11:28,519,Pershing Square N,40.751884,-73.977702,526,E 33 St & 5 Ave,40.747659,...,2014-01-01 00:00:00,2014-01-01 00:00:00,-3.6,44,0.0,15.0,281,0,0,Wednesday
4,660,2014-01-01 00:05:18,2014-01-01 00:16:18,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,436,Hancock St & Bedford Ave,40.682166,...,2014-01-01 00:00:00,2014-01-01 00:00:00,-3.6,44,0.0,15.0,281,0,0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964248,244,2014-03-31 23:57:47,2014-04-01 00:01:51,347,W Houston St & Hudson St,40.728739,-74.007488,368,Carmine St & 6 Ave,40.730386,...,2014-03-31 23:00:00,2014-03-31 23:00:00,4.5,60,0.0,15.5,1,0,23,Monday
964249,244,2014-03-31 23:57:55,2014-04-01 00:01:59,347,W Houston St & Hudson St,40.728739,-74.007488,212,W 16 St & The High Line,40.743349,...,2014-03-31 23:00:00,2014-03-31 23:00:00,4.5,60,0.0,15.5,1,0,23,Monday
964250,509,2014-03-31 23:58:19,2014-04-01 00:06:48,285,Broadway & E 14 St,40.734546,-73.990741,546,E 30 St & Park Ave S,40.744449,...,2014-03-31 23:00:00,2014-03-31 23:00:00,4.5,60,0.0,15.5,1,0,23,Monday
964251,649,2014-03-31 23:59:40,2014-04-01 00:10:29,403,E 2 St & 2 Ave,40.725029,-73.990697,461,E 20 St & 2 Ave,40.735877,...,2014-03-31 23:00:00,2014-03-31 23:00:00,4.5,60,0.0,15.5,1,0,23,Monday
964252,255,2014-03-31 23:59:54,2014-04-01 00:04:09,120,Lexington Ave & Classon Ave,40.686768,-73.959282,396,Lefferts Pl & Franklin Ave,40.680342,...,2014-03-31 23:00:00,2014-03-31 23:00:00,4.5,60,0.0,15.5,1,0,23,Monday

In [28]:
# What day of the week does each trip start

fe["Day_Type"] = fe["Start_Time"].dt.dayofweek.map(
    lambda x: "Weekend" if x >= 5 else "Weekday"
)
fe

,Trip_Duration,Start_Time,Stop_Time,Start_Station_Id,Start_Station_Name,Start_Station_Latitude,Start_Station_Longitude,End_Station_Id,End_Station_Name,End_Station_Latitude,...,Precipitation (Mm),Wind_Speed_10M (Km/H),Wind_Direction_10M (°),Weather_Code (Wmo Code),Start_Hour,Day_of_Week,Day_Type,Month,Peak_Hour,Season
0,471,2014-01-01 00:00:06,2014-01-01 00:07:57,2009,Catherine St & Monroe St,40.711174,-73.996826,263,Elizabeth St & Hester St,40.717290,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
1,1494,2014-01-01 00:00:38,2014-01-01 00:25:32,536,1 Ave & E 30 St,40.741444,-73.975361,259,South St & Whitehall St,40.701221,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
2,464,2014-01-01 00:03:59,2014-01-01 00:11:43,228,E 48 St & 3 Ave,40.754601,-73.971879,2022,E 59 St & Sutton Pl,40.758491,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
3,373,2014-01-01 00:05:15,2014-01-01 00:11:28,519,Pershing Square N,40.751884,-73.977702,526,E 33 St & 5 Ave,40.747659,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
4,660,2014-01-01 00:05:18,2014-01-01 00:16:18,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,436,Hancock St & Bedford Ave,40.682166,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964248,244,2014-03-31 23:57:47,2014-04-01 00:01:51,347,W Houston St & Hudson St,40.728739,-74.007488,368,Carmine St & 6 Ave,40.730386,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964249,244,2014-03-31 23:57:55,2014-04-01 00:01:59,347,W Houston St & Hudson St,40.728739,-74.007488,212,W 16 St & The High Line,40.743349,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964250,509,2014-03-31 23:58:19,2014-04-01 00:06:48,285,Broadway & E 14 St,40.734546,-73.990741,546,E 30 St & Park Ave S,40.744449,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964251,649,2014-03-31 23:59:40,2014-04-01 00:10:29,403,E 2 St & 2 Ave,40.725029,-73.990697,461,E 20 St & 2 Ave,40.735877,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964252,255,2014-03-31 23:59:54,2014-04-01 00:04:09,120,Lexington Ave & Classon Ave,40.686768,-73.959282,396,Lefferts Pl & Franklin Ave,40.680342,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring

In [29]:
# Is the trip taken on a weekday or weekend 

fe["Month"] = fe["Start_Time"].dt.month
fe

,Trip_Duration,Start_Time,Stop_Time,Start_Station_Id,Start_Station_Name,Start_Station_Latitude,Start_Station_Longitude,End_Station_Id,End_Station_Name,End_Station_Latitude,...,Precipitation (Mm),Wind_Speed_10M (Km/H),Wind_Direction_10M (°),Weather_Code (Wmo Code),Start_Hour,Day_of_Week,Day_Type,Month,Peak_Hour,Season
0,471,2014-01-01 00:00:06,2014-01-01 00:07:57,2009,Catherine St & Monroe St,40.711174,-73.996826,263,Elizabeth St & Hester St,40.717290,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
1,1494,2014-01-01 00:00:38,2014-01-01 00:25:32,536,1 Ave & E 30 St,40.741444,-73.975361,259,South St & Whitehall St,40.701221,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
2,464,2014-01-01 00:03:59,2014-01-01 00:11:43,228,E 48 St & 3 Ave,40.754601,-73.971879,2022,E 59 St & Sutton Pl,40.758491,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
3,373,2014-01-01 00:05:15,2014-01-01 00:11:28,519,Pershing Square N,40.751884,-73.977702,526,E 33 St & 5 Ave,40.747659,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
4,660,2014-01-01 00:05:18,2014-01-01 00:16:18,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,436,Hancock St & Bedford Ave,40.682166,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964248,244,2014-03-31 23:57:47,2014-04-01 00:01:51,347,W Houston St & Hudson St,40.728739,-74.007488,368,Carmine St & 6 Ave,40.730386,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964249,244,2014-03-31 23:57:55,2014-04-01 00:01:59,347,W Houston St & Hudson St,40.728739,-74.007488,212,W 16 St & The High Line,40.743349,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964250,509,2014-03-31 23:58:19,2014-04-01 00:06:48,285,Broadway & E 14 St,40.734546,-73.990741,546,E 30 St & Park Ave S,40.744449,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964251,649,2014-03-31 23:59:40,2014-04-01 00:10:29,403,E 2 St & 2 Ave,40.725029,-73.990697,461,E 20 St & 2 Ave,40.735877,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964252,255,2014-03-31 23:59:54,2014-04-01 00:04:09,120,Lexington Ave & Classon Ave,40.686768,-73.959282,396,Lefferts Pl & Franklin Ave,40.680342,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring

In [30]:
# Peak-hour feature

fe["Peak_Hour"] = fe["Start_Hour"].isin(
    [7, 8, 9, 17, 18, 19]
)
fe

,Trip_Duration,Start_Time,Stop_Time,Start_Station_Id,Start_Station_Name,Start_Station_Latitude,Start_Station_Longitude,End_Station_Id,End_Station_Name,End_Station_Latitude,...,Precipitation (Mm),Wind_Speed_10M (Km/H),Wind_Direction_10M (°),Weather_Code (Wmo Code),Start_Hour,Day_of_Week,Day_Type,Month,Peak_Hour,Season
0,471,2014-01-01 00:00:06,2014-01-01 00:07:57,2009,Catherine St & Monroe St,40.711174,-73.996826,263,Elizabeth St & Hester St,40.717290,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
1,1494,2014-01-01 00:00:38,2014-01-01 00:25:32,536,1 Ave & E 30 St,40.741444,-73.975361,259,South St & Whitehall St,40.701221,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
2,464,2014-01-01 00:03:59,2014-01-01 00:11:43,228,E 48 St & 3 Ave,40.754601,-73.971879,2022,E 59 St & Sutton Pl,40.758491,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
3,373,2014-01-01 00:05:15,2014-01-01 00:11:28,519,Pershing Square N,40.751884,-73.977702,526,E 33 St & 5 Ave,40.747659,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
4,660,2014-01-01 00:05:18,2014-01-01 00:16:18,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,436,Hancock St & Bedford Ave,40.682166,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964248,244,2014-03-31 23:57:47,2014-04-01 00:01:51,347,W Houston St & Hudson St,40.728739,-74.007488,368,Carmine St & 6 Ave,40.730386,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964249,244,2014-03-31 23:57:55,2014-04-01 00:01:59,347,W Houston St & Hudson St,40.728739,-74.007488,212,W 16 St & The High Line,40.743349,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964250,509,2014-03-31 23:58:19,2014-04-01 00:06:48,285,Broadway & E 14 St,40.734546,-73.990741,546,E 30 St & Park Ave S,40.744449,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964251,649,2014-03-31 23:59:40,2014-04-01 00:10:29,403,E 2 St & 2 Ave,40.725029,-73.990697,461,E 20 St & 2 Ave,40.735877,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964252,255,2014-03-31 23:59:54,2014-04-01 00:04:09,120,Lexington Ave & Classon Ave,40.686768,-73.959282,396,Lefferts Pl & Franklin Ave,40.680342,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring

In [26]:
fe["Season"] = fe["Month"].map({
    1: "Winter",
    2: "Winter",
    3: "Spring"
})
fe

,Trip_Duration,Start_Time,Stop_Time,Start_Station_Id,Start_Station_Name,Start_Station_Latitude,Start_Station_Longitude,End_Station_Id,End_Station_Name,End_Station_Latitude,...,Precipitation (Mm),Wind_Speed_10M (Km/H),Wind_Direction_10M (°),Weather_Code (Wmo Code),Start_Hour,Day_of_Week,Day_Type,Month,Peak_Hour,Season
0,471,2014-01-01 00:00:06,2014-01-01 00:07:57,2009,Catherine St & Monroe St,40.711174,-73.996826,263,Elizabeth St & Hester St,40.717290,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
1,1494,2014-01-01 00:00:38,2014-01-01 00:25:32,536,1 Ave & E 30 St,40.741444,-73.975361,259,South St & Whitehall St,40.701221,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
2,464,2014-01-01 00:03:59,2014-01-01 00:11:43,228,E 48 St & 3 Ave,40.754601,-73.971879,2022,E 59 St & Sutton Pl,40.758491,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
3,373,2014-01-01 00:05:15,2014-01-01 00:11:28,519,Pershing Square N,40.751884,-73.977702,526,E 33 St & 5 Ave,40.747659,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
4,660,2014-01-01 00:05:18,2014-01-01 00:16:18,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,436,Hancock St & Bedford Ave,40.682166,...,0.0,15.0,281,0,0,Wednesday,Weekday,1,False,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964248,244,2014-03-31 23:57:47,2014-04-01 00:01:51,347,W Houston St & Hudson St,40.728739,-74.007488,368,Carmine St & 6 Ave,40.730386,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964249,244,2014-03-31 23:57:55,2014-04-01 00:01:59,347,W Houston St & Hudson St,40.728739,-74.007488,212,W 16 St & The High Line,40.743349,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964250,509,2014-03-31 23:58:19,2014-04-01 00:06:48,285,Broadway & E 14 St,40.734546,-73.990741,546,E 30 St & Park Ave S,40.744449,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964251,649,2014-03-31 23:59:40,2014-04-01 00:10:29,403,E 2 St & 2 Ave,40.725029,-73.990697,461,E 20 St & 2 Ave,40.735877,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring
964252,255,2014-03-31 23:59:54,2014-04-01 00:04:09,120,Lexington Ave & Classon Ave,40.686768,-73.959282,396,Lefferts Pl & Franklin Ave,40.680342,...,0.0,15.5,1,0,23,Monday,Weekday,3,False,Spring

In [31]:
fe.to_csv("2.1_Advanced_Clean_data.csv",index = True)